
//! Autogenerated weights for pallet_zk_verifier
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 53.0.0
//! DATE: 2026-09-27, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `developer laptop`, CPU: `Intel(R) Core(TM) Ultra 9 275HX` (single-threaded Halo2 verification)
//! EXECUTION: , WASM-EXECUTION: Compiled, CHAIN: Some("dev"), DB CACHE: 1024

// Executed Command:
// ./target/release/arxon-node
// benchmark
// pallet
// --chain
// dev
// --pallet
// pallet_zk_verifier
// --extrinsic
// *
// --steps
// 50
// --repeat
// 20
// --template
// scripts/frame-weight-template.hbs
// --output
// template/pallets/zk-verifier/src/weights.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use core::marker::PhantomData;

/// Weight functions needed for pallet_zk_verifier.
pub trait WeightInfo {
	fn set_circuit_enabled() -> Weight;
	fn verify_privacy_flag_enforcement(n: u32, ) -> Weight;
	fn verify_balance_integrity() -> Weight;
	fn verify_nullifier_derivation(n: u32, ) -> Weight;
	fn verify_ptr_generation() -> Weight;
	fn verify_disclosure_proof() -> Weight;
	fn verify_trust_registry_membership() -> Weight;
}

/// Weights for pallet_zk_verifier using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	/// Storage: `ZkVerifier::Circuits` (r:1 w:1)
	/// Proof: `ZkVerifier::Circuits` (`max_values`: None, `max_size`: Some(42), added: 2517, mode: `MaxEncodedLen`)
	/// Storage: `System::Number` (r:1 w:0)
	/// Proof: `System::Number` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `System::ExecutionPhase` (r:1 w:0)
	/// Proof: `System::ExecutionPhase` (`max_values`: Some(1), `max_size`: Some(5), added: 500, mode: `MaxEncodedLen`)
	/// Storage: `System::EventCount` (r:1 w:1)
	/// Proof: `System::EventCount` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `System::Events` (r:1 w:1)
	/// Proof: `System::Events` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	fn set_circuit_enabled() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `267`
		//  Estimated: `3507`
		// Minimum execution time: 13_484_000 picoseconds.
		Weight::from_parts(14_223_000, 3507)
			.saturating_add(T::DbWeight::get().reads(5_u64))
			.saturating_add(T::DbWeight::get().writes(3_u64))
	}
	/// Storage: `ZkVerifier::Circuits` (r:1 w:0)
	/// Proof: `ZkVerifier::Circuits` (`max_values`: None, `max_size`: Some(42), added: 2517, mode: `MaxEncodedLen`)
	/// Storage: `ZkVerifier::VerificationCount` (r:1 w:1)
	/// Proof: `ZkVerifier::VerificationCount` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// The range of component `n` is `[1, 2]`.
	fn verify_privacy_flag_enforcement(n: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `248`
		//  Estimated: `3507`
		// Minimum execution time: 9_188_636_000 picoseconds.
		Weight::from_parts(7_842_571_461, 3507)
			// Standard Error: 30_917_363
			.saturating_add(Weight::from_parts(2_343_649_469, 0).saturating_mul(n.into()))
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `ZkVerifier::Circuits` (r:1 w:0)
	/// Proof: `ZkVerifier::Circuits` (`max_values`: None, `max_size`: Some(42), added: 2517, mode: `MaxEncodedLen`)
	/// Storage: `ZkVerifier::VerificationCount` (r:1 w:1)
	/// Proof: `ZkVerifier::VerificationCount` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	fn verify_balance_integrity() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `211`
		//  Estimated: `3507`
		// Minimum execution time: 9_846_915_000 picoseconds.
		Weight::from_parts(10_162_957_000, 3507)
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `ZkVerifier::Circuits` (r:1 w:0)
	/// Proof: `ZkVerifier::Circuits` (`max_values`: None, `max_size`: Some(42), added: 2517, mode: `MaxEncodedLen`)
	/// Storage: `ZkVerifier::VerificationCount` (r:1 w:1)
	/// Proof: `ZkVerifier::VerificationCount` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// The range of component `n` is `[1, 2]`.
	fn verify_nullifier_derivation(n: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `211`
		//  Estimated: `3507`
		// Minimum execution time: 21_200_822_000 picoseconds.
		Weight::from_parts(17_516_427_606, 3507)
			// Standard Error: 171_567_301
			.saturating_add(Weight::from_parts(6_711_365_046, 0).saturating_mul(n.into()))
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `ZkVerifier::Circuits` (r:1 w:0)
	/// Proof: `ZkVerifier::Circuits` (`max_values`: None, `max_size`: Some(42), added: 2517, mode: `MaxEncodedLen`)
	/// Storage: `ZkVerifier::VerificationCount` (r:1 w:1)
	/// Proof: `ZkVerifier::VerificationCount` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	fn verify_ptr_generation() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `248`
		//  Estimated: `3507`
		// Minimum execution time: 10_454_935_000 picoseconds.
		Weight::from_parts(11_170_128_000, 3507)
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `ZkVerifier::Circuits` (r:1 w:0)
	/// Proof: `ZkVerifier::Circuits` (`max_values`: None, `max_size`: Some(42), added: 2517, mode: `MaxEncodedLen`)
	/// Storage: `ZkVerifier::VerificationCount` (r:1 w:1)
	/// Proof: `ZkVerifier::VerificationCount` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	fn verify_disclosure_proof() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `211`
		//  Estimated: `3507`
		// Minimum execution time: 10_053_293_000 picoseconds.
		Weight::from_parts(10_397_092_000, 3507)
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `ZkVerifier::Circuits` (r:1 w:0)
	/// Proof: `ZkVerifier::Circuits` (`max_values`: None, `max_size`: Some(42), added: 2517, mode: `MaxEncodedLen`)
	/// Storage: `ZkVerifier::VerificationCount` (r:1 w:1)
	/// Proof: `ZkVerifier::VerificationCount` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	fn verify_trust_registry_membership() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `211`
		//  Estimated: `3507`
		// Minimum execution time: 15_280_854_000 picoseconds.
		Weight::from_parts(15_847_125_000, 3507)
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
}

// For backwards compatibility and tests
impl WeightInfo for () {
	/// Storage: `ZkVerifier::Circuits` (r:1 w:1)
	/// Proof: `ZkVerifier::Circuits` (`max_values`: None, `max_size`: Some(42), added: 2517, mode: `MaxEncodedLen`)
	/// Storage: `System::Number` (r:1 w:0)
	/// Proof: `System::Number` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `System::ExecutionPhase` (r:1 w:0)
	/// Proof: `System::ExecutionPhase` (`max_values`: Some(1), `max_size`: Some(5), added: 500, mode: `MaxEncodedLen`)
	/// Storage: `System::EventCount` (r:1 w:1)
	/// Proof: `System::EventCount` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `System::Events` (r:1 w:1)
	/// Proof: `System::Events` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	fn set_circuit_enabled() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `267`
		//  Estimated: `3507`
		// Minimum execution time: 13_484_000 picoseconds.
		Weight::from_parts(14_223_000, 3507)
			.saturating_add(RocksDbWeight::get().reads(5_u64))
			.saturating_add(RocksDbWeight::get().writes(3_u64))
	}
	/// Storage: `ZkVerifier::Circuits` (r:1 w:0)
	/// Proof: `ZkVerifier::Circuits` (`max_values`: None, `max_size`: Some(42), added: 2517, mode: `MaxEncodedLen`)
	/// Storage: `ZkVerifier::VerificationCount` (r:1 w:1)
	/// Proof: `ZkVerifier::VerificationCount` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// The range of component `n` is `[1, 2]`.
	fn verify_privacy_flag_enforcement(n: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `248`
		//  Estimated: `3507`
		// Minimum execution time: 9_188_636_000 picoseconds.
		Weight::from_parts(7_842_571_461, 3507)
			// Standard Error: 30_917_363
			.saturating_add(Weight::from_parts(2_343_649_469, 0).saturating_mul(n.into()))
			.saturating_add(RocksDbWeight::get().reads(2_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `ZkVerifier::Circuits` (r:1 w:0)
	/// Proof: `ZkVerifier::Circuits` (`max_values`: None, `max_size`: Some(42), added: 2517, mode: `MaxEncodedLen`)
	/// Storage: `ZkVerifier::VerificationCount` (r:1 w:1)
	/// Proof: `ZkVerifier::VerificationCount` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	fn verify_balance_integrity() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `211`
		//  Estimated: `3507`
		// Minimum execution time: 9_846_915_000 picoseconds.
		Weight::from_parts(10_162_957_000, 3507)
			.saturating_add(RocksDbWeight::get().reads(2_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `ZkVerifier::Circuits` (r:1 w:0)
	/// Proof: `ZkVerifier::Circuits` (`max_values`: None, `max_size`: Some(42), added: 2517, mode: `MaxEncodedLen`)
	/// Storage: `ZkVerifier::VerificationCount` (r:1 w:1)
	/// Proof: `ZkVerifier::VerificationCount` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// The range of component `n` is `[1, 2]`.
	fn verify_nullifier_derivation(n: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `211`
		//  Estimated: `3507`
		// Minimum execution time: 21_200_822_000 picoseconds.
		Weight::from_parts(17_516_427_606, 3507)
			// Standard Error: 171_567_301
			.saturating_add(Weight::from_parts(6_711_365_046, 0).saturating_mul(n.into()))
			.saturating_add(RocksDbWeight::get().reads(2_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `ZkVerifier::Circuits` (r:1 w:0)
	/// Proof: `ZkVerifier::Circuits` (`max_values`: None, `max_size`: Some(42), added: 2517, mode: `MaxEncodedLen`)
	/// Storage: `ZkVerifier::VerificationCount` (r:1 w:1)
	/// Proof: `ZkVerifier::VerificationCount` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	fn verify_ptr_generation() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `248`
		//  Estimated: `3507`
		// Minimum execution time: 10_454_935_000 picoseconds.
		Weight::from_parts(11_170_128_000, 3507)
			.saturating_add(RocksDbWeight::get().reads(2_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `ZkVerifier::Circuits` (r:1 w:0)
	/// Proof: `ZkVerifier::Circuits` (`max_values`: None, `max_size`: Some(42), added: 2517, mode: `MaxEncodedLen`)
	/// Storage: `ZkVerifier::VerificationCount` (r:1 w:1)
	/// Proof: `ZkVerifier::VerificationCount` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	fn verify_disclosure_proof() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `211`
		//  Estimated: `3507`
		// Minimum execution time: 10_053_293_000 picoseconds.
		Weight::from_parts(10_397_092_000, 3507)
			.saturating_add(RocksDbWeight::get().reads(2_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `ZkVerifier::Circuits` (r:1 w:0)
	/// Proof: `ZkVerifier::Circuits` (`max_values`: None, `max_size`: Some(42), added: 2517, mode: `MaxEncodedLen`)
	/// Storage: `ZkVerifier::VerificationCount` (r:1 w:1)
	/// Proof: `ZkVerifier::VerificationCount` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	fn verify_trust_registry_membership() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `211`
		//  Estimated: `3507`
		// Minimum execution time: 15_280_854_000 picoseconds.
		Weight::from_parts(15_847_125_000, 3507)
			.saturating_add(RocksDbWeight::get().reads(2_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
}
