//! Weights.
//!
//! The light extrinsics are benchmarked directly ([`benchmarked`], generated by
//! `arxon-node benchmark pallet --pallet pallet_privacy`). A bundle's weight is
//! composed from measured primitives, because its cost is dominated by host
//! function proof verifications and note tree inserts that the consuming
//! pallets expose as weights: one Circuit 3 verification per input, one
//! Circuit 1 verification per output, one Circuit 2 verification, one nullifier
//! mark per input, one insert per output, plus the receipt and membership
//! attachments when present, plus the storage the pallet itself touches.

pub mod benchmarked;

use core::marker::PhantomData;

use arxon_zk_primitives::CircuitId;
use frame_support::{traits::Get, weights::Weight};
use pallet_note_tree::{MerkleTree, TreeId};
use pallet_nullifier_registry::NullifierSet;
use pallet_zk_verifier::VerifyProof;

use crate::{Config, ReceiptSink};

/// Weight functions needed for pallet_privacy.
pub trait WeightInfo {
	/// `set_privacy_default`.
	fn set_privacy_default() -> Weight;
	/// `set_balance_visibility`.
	fn set_balance_visibility() -> Weight;
	/// `register_shielded_key`.
	fn register_shielded_key() -> Weight;
	/// `shield` with `outputs` notes.
	fn shield(outputs: u32) -> Weight;
	/// `unshield` with `inputs` spent notes and `outputs` change notes.
	fn unshield(inputs: u32, outputs: u32) -> Weight;
	/// `submit_private_transfer` with `inputs` spent and `outputs` created notes and the
	/// optional receipt and membership attachments.
	fn submit_private_transfer(inputs: u32, outputs: u32, ptr: bool, compliance: bool) -> Weight;
	/// `set_arx20_unit`.
	fn set_arx20_unit() -> Weight;
}

/// Composed weights: measured light extrinsics plus measured primitives of the ZK pallets.
pub struct SubstrateWeight<T>(PhantomData<T>);

/// Ref time the pallet spends outside storage and primitives per bundle: SCALE
/// work on the arguments and the blake2 bundle digest over at most a few KiB.
/// A fixed margin, deliberately above what the benchmark laptop measures.
const BUNDLE_COMPUTE: u64 = 200_000_000;

impl<T: Config> SubstrateWeight<T> {
	fn bundle(inputs: u32, outputs: u32, transparent: bool, ptr: bool, compliance: bool) -> Weight {
		let db = T::DbWeight::get();
		// Checks: duplicate bundle, known anchor, pool balance, spent nullifiers,
		// duplicate leaves, revealed party lookups, membership root; then the
		// bundle record and the shielded counter.
		// Plus the asset's unit and, on bundles that spend, the hide-balance flag
		// (value and pending change) of the recipient, the signer and the fee
		// recipient, and the relayer fee transfer out of the pool. Charged whether
		// or not the bundle carries a fee, so the weight does not depend on
		// arguments the call macro cannot see cheaply. ARX-20 bundles also read
		// the token's code size and, for a 23-byte code, the code itself (the
		// EIP-7702 check); native bundles pay for it too.
		let spends = inputs > 0;
		let reads = 1
			+ u64::from(spends)
			+ u64::from(transparent)
			+ 2 * u64::from(inputs)
			+ 2 * u64::from(outputs)
			+ 1 + u64::from(compliance)
			+ 1 + 2 + if spends { 3 * 2 + 2 } else { 0 };
		let writes = 2 + if spends { 2 } else { 0 };
		let mut w =
			Weight::from_parts(BUNDLE_COMPUTE, 0).saturating_add(db.reads_writes(reads, writes));
		if inputs > 0 {
			w = w.saturating_add(T::ZkVerifier::verify_weight(
				CircuitId::NullifierDerivation,
				inputs,
			));
			w = w.saturating_add(T::Nullifiers::mark_spent_weight().saturating_mul(inputs as u64));
		}
		if outputs > 0 {
			w = w.saturating_add(T::ZkVerifier::verify_weight(
				CircuitId::PrivacyFlagEnforcement,
				outputs,
			));
			w = w.saturating_add(
				T::Trees::insert_weight(TreeId::Note).saturating_mul(outputs as u64),
			);
		}
		w = w.saturating_add(T::ZkVerifier::verify_weight(CircuitId::BalanceIntegrity, 1));
		if transparent {
			// fungible transfer between the depositor or recipient and the pool account.
			w = w.saturating_add(db.reads_writes(2, 2));
		}
		if ptr {
			w = w.saturating_add(T::ZkVerifier::verify_weight(CircuitId::PtrGeneration, 1));
			w = w.saturating_add(T::Receipts::record_weight());
		}
		if compliance {
			w = w.saturating_add(T::ZkVerifier::verify_weight(
				CircuitId::TrustRegistryMembership,
				1,
			));
		}
		w
	}
}

impl<T: Config> WeightInfo for SubstrateWeight<T> {
	fn set_privacy_default() -> Weight {
		<benchmarked::SubstrateWeight<T> as benchmarked::WeightInfo>::set_privacy_default()
	}

	fn set_balance_visibility() -> Weight {
		<benchmarked::SubstrateWeight<T> as benchmarked::WeightInfo>::set_balance_visibility()
	}

	fn register_shielded_key() -> Weight {
		<benchmarked::SubstrateWeight<T> as benchmarked::WeightInfo>::register_shielded_key()
	}

	fn shield(outputs: u32) -> Weight {
		Self::bundle(0, outputs, true, false, false)
	}

	fn unshield(inputs: u32, outputs: u32) -> Weight {
		Self::bundle(inputs, outputs, true, false, false)
	}

	fn submit_private_transfer(inputs: u32, outputs: u32, ptr: bool, compliance: bool) -> Weight {
		Self::bundle(inputs, outputs, false, ptr, compliance)
	}

	fn set_arx20_unit() -> Weight {
		<benchmarked::SubstrateWeight<T> as benchmarked::WeightInfo>::set_arx20_unit()
	}
}

/// Pre-measurement placeholders (20 ms per verification and per insert), kept for mocks.
const VERIFY: u64 = 20_000_000_000;
const INSERT: u64 = 20_000_000_000;
const BASE: u64 = 50_000_000;

fn placeholder_bundle(inputs: u32, outputs: u32, extra_verifications: u32) -> Weight {
	let verifications = (inputs + outputs + 1 + extra_verifications) as u64;
	Weight::from_parts(
		BASE + VERIFY * verifications + INSERT * outputs as u64,
		16_384 + 4_096 * (inputs + outputs) as u64,
	)
}

impl WeightInfo for () {
	fn set_privacy_default() -> Weight {
		Weight::from_parts(BASE, 1_024)
	}

	fn set_balance_visibility() -> Weight {
		Weight::from_parts(BASE, 1_024)
	}

	fn register_shielded_key() -> Weight {
		Weight::from_parts(BASE, 2_048)
	}

	fn shield(outputs: u32) -> Weight {
		placeholder_bundle(0, outputs, 0)
	}

	fn unshield(inputs: u32, outputs: u32) -> Weight {
		placeholder_bundle(inputs, outputs, 0)
	}

	fn submit_private_transfer(inputs: u32, outputs: u32, ptr: bool, compliance: bool) -> Weight {
		placeholder_bundle(inputs, outputs, ptr as u32 + compliance as u32)
	}

	fn set_arx20_unit() -> Weight {
		Weight::from_parts(BASE, 2_048)
	}
}
