
//! Autogenerated weights for pallet_note_tree
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 53.0.0
//! DATE: 2026-09-27, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `developer laptop`, CPU: `Intel(R) Core(TM) Ultra 9 275HX` (single-threaded Halo2 verification)
//! EXECUTION: , WASM-EXECUTION: Compiled, CHAIN: Some("dev"), DB CACHE: 1024

// Executed Command:
// ./target/release/arxon-node
// benchmark
// pallet
// --chain
// dev
// --pallet
// pallet_note_tree
// --extrinsic
// *
// --steps
// 50
// --repeat
// 20
// --template
// scripts/frame-weight-template.hbs
// --output
// template/pallets/note-tree/src/weights.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use core::marker::PhantomData;

/// Weight functions needed for pallet_note_tree.
pub trait WeightInfo {
	fn add_member() -> Weight;
	fn insert() -> Weight;
}

/// Weights for pallet_note_tree using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	/// Storage: `NoteTree::KnownLeaves` (r:1 w:1)
	/// Proof: `NoteTree::KnownLeaves` (`max_values`: None, `max_size`: Some(65), added: 2540, mode: `MaxEncodedLen`)
	/// Storage: `NoteTree::NextLeafIndex` (r:1 w:1)
	/// Proof: `NoteTree::NextLeafIndex` (`max_values`: None, `max_size`: Some(17), added: 2492, mode: `MaxEncodedLen`)
	/// Storage: `NoteTree::Zeros` (r:16 w:0)
	/// Proof: `NoteTree::Zeros` (`max_values`: None, `max_size`: Some(50), added: 2525, mode: `MaxEncodedLen`)
	/// Storage: `NoteTree::RootCursor` (r:1 w:1)
	/// Proof: `NoteTree::RootCursor` (`max_values`: None, `max_size`: Some(13), added: 2488, mode: `MaxEncodedLen`)
	/// Storage: `NoteTree::RootHistory` (r:1 w:1)
	/// Proof: `NoteTree::RootHistory` (`max_values`: None, `max_size`: Some(53), added: 2528, mode: `MaxEncodedLen`)
	/// Storage: `System::Number` (r:1 w:0)
	/// Proof: `System::Number` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `System::ExecutionPhase` (r:1 w:0)
	/// Proof: `System::ExecutionPhase` (`max_values`: Some(1), `max_size`: Some(5), added: 500, mode: `MaxEncodedLen`)
	/// Storage: `System::EventCount` (r:1 w:1)
	/// Proof: `System::EventCount` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `System::Events` (r:1 w:1)
	/// Proof: `System::Events` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `NoteTree::KnownRoots` (r:0 w:2)
	/// Proof: `NoteTree::KnownRoots` (`max_values`: None, `max_size`: Some(61), added: 2536, mode: `MaxEncodedLen`)
	/// Storage: `NoteTree::FilledSubtrees` (r:0 w:16)
	/// Proof: `NoteTree::FilledSubtrees` (`max_values`: None, `max_size`: Some(50), added: 2525, mode: `MaxEncodedLen`)
	/// Storage: `NoteTree::CurrentRoot` (r:0 w:1)
	/// Proof: `NoteTree::CurrentRoot` (`max_values`: None, `max_size`: Some(41), added: 2516, mode: `MaxEncodedLen`)
	fn add_member() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `972`
		//  Estimated: `41390`
		// Minimum execution time: 1_646_637_000 picoseconds.
		Weight::from_parts(1_794_334_000, 41390)
			.saturating_add(T::DbWeight::get().reads(24_u64))
			.saturating_add(T::DbWeight::get().writes(25_u64))
	}
	/// Storage: `NoteTree::KnownLeaves` (r:1 w:1)
	/// Proof: `NoteTree::KnownLeaves` (`max_values`: None, `max_size`: Some(65), added: 2540, mode: `MaxEncodedLen`)
	/// Storage: `NoteTree::NextLeafIndex` (r:1 w:1)
	/// Proof: `NoteTree::NextLeafIndex` (`max_values`: None, `max_size`: Some(17), added: 2492, mode: `MaxEncodedLen`)
	/// Storage: `NoteTree::Zeros` (r:32 w:0)
	/// Proof: `NoteTree::Zeros` (`max_values`: None, `max_size`: Some(50), added: 2525, mode: `MaxEncodedLen`)
	/// Storage: `NoteTree::RootCursor` (r:1 w:1)
	/// Proof: `NoteTree::RootCursor` (`max_values`: None, `max_size`: Some(13), added: 2488, mode: `MaxEncodedLen`)
	/// Storage: `NoteTree::RootHistory` (r:1 w:1)
	/// Proof: `NoteTree::RootHistory` (`max_values`: None, `max_size`: Some(53), added: 2528, mode: `MaxEncodedLen`)
	/// Storage: `System::Number` (r:1 w:0)
	/// Proof: `System::Number` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `System::ExecutionPhase` (r:1 w:0)
	/// Proof: `System::ExecutionPhase` (`max_values`: Some(1), `max_size`: Some(5), added: 500, mode: `MaxEncodedLen`)
	/// Storage: `System::EventCount` (r:1 w:1)
	/// Proof: `System::EventCount` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `System::Events` (r:1 w:1)
	/// Proof: `System::Events` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `NoteTree::KnownRoots` (r:0 w:2)
	/// Proof: `NoteTree::KnownRoots` (`max_values`: None, `max_size`: Some(61), added: 2536, mode: `MaxEncodedLen`)
	/// Storage: `NoteTree::FilledSubtrees` (r:0 w:32)
	/// Proof: `NoteTree::FilledSubtrees` (`max_values`: None, `max_size`: Some(50), added: 2525, mode: `MaxEncodedLen`)
	/// Storage: `NoteTree::CurrentRoot` (r:0 w:1)
	/// Proof: `NoteTree::CurrentRoot` (`max_values`: None, `max_size`: Some(41), added: 2516, mode: `MaxEncodedLen`)
	fn insert() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1710`
		//  Estimated: `81790`
		// Minimum execution time: 3_361_474_000 picoseconds.
		Weight::from_parts(3_606_866_000, 81790)
			.saturating_add(T::DbWeight::get().reads(40_u64))
			.saturating_add(T::DbWeight::get().writes(41_u64))
	}
}

// For backwards compatibility and tests
impl WeightInfo for () {
	/// Storage: `NoteTree::KnownLeaves` (r:1 w:1)
	/// Proof: `NoteTree::KnownLeaves` (`max_values`: None, `max_size`: Some(65), added: 2540, mode: `MaxEncodedLen`)
	/// Storage: `NoteTree::NextLeafIndex` (r:1 w:1)
	/// Proof: `NoteTree::NextLeafIndex` (`max_values`: None, `max_size`: Some(17), added: 2492, mode: `MaxEncodedLen`)
	/// Storage: `NoteTree::Zeros` (r:16 w:0)
	/// Proof: `NoteTree::Zeros` (`max_values`: None, `max_size`: Some(50), added: 2525, mode: `MaxEncodedLen`)
	/// Storage: `NoteTree::RootCursor` (r:1 w:1)
	/// Proof: `NoteTree::RootCursor` (`max_values`: None, `max_size`: Some(13), added: 2488, mode: `MaxEncodedLen`)
	/// Storage: `NoteTree::RootHistory` (r:1 w:1)
	/// Proof: `NoteTree::RootHistory` (`max_values`: None, `max_size`: Some(53), added: 2528, mode: `MaxEncodedLen`)
	/// Storage: `System::Number` (r:1 w:0)
	/// Proof: `System::Number` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `System::ExecutionPhase` (r:1 w:0)
	/// Proof: `System::ExecutionPhase` (`max_values`: Some(1), `max_size`: Some(5), added: 500, mode: `MaxEncodedLen`)
	/// Storage: `System::EventCount` (r:1 w:1)
	/// Proof: `System::EventCount` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `System::Events` (r:1 w:1)
	/// Proof: `System::Events` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `NoteTree::KnownRoots` (r:0 w:2)
	/// Proof: `NoteTree::KnownRoots` (`max_values`: None, `max_size`: Some(61), added: 2536, mode: `MaxEncodedLen`)
	/// Storage: `NoteTree::FilledSubtrees` (r:0 w:16)
	/// Proof: `NoteTree::FilledSubtrees` (`max_values`: None, `max_size`: Some(50), added: 2525, mode: `MaxEncodedLen`)
	/// Storage: `NoteTree::CurrentRoot` (r:0 w:1)
	/// Proof: `NoteTree::CurrentRoot` (`max_values`: None, `max_size`: Some(41), added: 2516, mode: `MaxEncodedLen`)
	fn add_member() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `972`
		//  Estimated: `41390`
		// Minimum execution time: 1_646_637_000 picoseconds.
		Weight::from_parts(1_794_334_000, 41390)
			.saturating_add(RocksDbWeight::get().reads(24_u64))
			.saturating_add(RocksDbWeight::get().writes(25_u64))
	}
	/// Storage: `NoteTree::KnownLeaves` (r:1 w:1)
	/// Proof: `NoteTree::KnownLeaves` (`max_values`: None, `max_size`: Some(65), added: 2540, mode: `MaxEncodedLen`)
	/// Storage: `NoteTree::NextLeafIndex` (r:1 w:1)
	/// Proof: `NoteTree::NextLeafIndex` (`max_values`: None, `max_size`: Some(17), added: 2492, mode: `MaxEncodedLen`)
	/// Storage: `NoteTree::Zeros` (r:32 w:0)
	/// Proof: `NoteTree::Zeros` (`max_values`: None, `max_size`: Some(50), added: 2525, mode: `MaxEncodedLen`)
	/// Storage: `NoteTree::RootCursor` (r:1 w:1)
	/// Proof: `NoteTree::RootCursor` (`max_values`: None, `max_size`: Some(13), added: 2488, mode: `MaxEncodedLen`)
	/// Storage: `NoteTree::RootHistory` (r:1 w:1)
	/// Proof: `NoteTree::RootHistory` (`max_values`: None, `max_size`: Some(53), added: 2528, mode: `MaxEncodedLen`)
	/// Storage: `System::Number` (r:1 w:0)
	/// Proof: `System::Number` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `System::ExecutionPhase` (r:1 w:0)
	/// Proof: `System::ExecutionPhase` (`max_values`: Some(1), `max_size`: Some(5), added: 500, mode: `MaxEncodedLen`)
	/// Storage: `System::EventCount` (r:1 w:1)
	/// Proof: `System::EventCount` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `System::Events` (r:1 w:1)
	/// Proof: `System::Events` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `NoteTree::KnownRoots` (r:0 w:2)
	/// Proof: `NoteTree::KnownRoots` (`max_values`: None, `max_size`: Some(61), added: 2536, mode: `MaxEncodedLen`)
	/// Storage: `NoteTree::FilledSubtrees` (r:0 w:32)
	/// Proof: `NoteTree::FilledSubtrees` (`max_values`: None, `max_size`: Some(50), added: 2525, mode: `MaxEncodedLen`)
	/// Storage: `NoteTree::CurrentRoot` (r:0 w:1)
	/// Proof: `NoteTree::CurrentRoot` (`max_values`: None, `max_size`: Some(41), added: 2516, mode: `MaxEncodedLen`)
	fn insert() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1710`
		//  Estimated: `81790`
		// Minimum execution time: 3_361_474_000 picoseconds.
		Weight::from_parts(3_606_866_000, 81790)
			.saturating_add(RocksDbWeight::get().reads(40_u64))
			.saturating_add(RocksDbWeight::get().writes(41_u64))
	}
}
