//! Weights. `record` is benchmarked ([`benchmarked`], generated by
//! `arxon-node benchmark pallet --pallet pallet_ptr`); `disclose` is composed from
//! the measured Circuit 5 verification plus the storage it touches.

pub mod benchmarked;

use core::marker::PhantomData;

use arxon_zk_primitives::CircuitId;
use frame_support::{traits::Get, weights::Weight};
use pallet_zk_verifier::VerifyProof;

use crate::Config;

/// Weight functions needed for pallet_ptr.
pub trait WeightInfo {
	/// Recording one receipt commitment.
	fn record() -> Weight;
	/// `disclose`: one Circuit 5 verification plus bookkeeping.
	fn disclose() -> Weight;
}

/// Composed weights.
pub struct SubstrateWeight<T>(PhantomData<T>);

/// Ref time for the audience digest, field checks and public input assembly.
const DISCLOSE_COMPUTE: u64 = 100_000_000;

impl<T: Config> WeightInfo for SubstrateWeight<T> {
	fn record() -> Weight {
		<benchmarked::SubstrateWeight<T> as benchmarked::WeightInfo>::record()
	}

	fn disclose() -> Weight {
		// Receipt lookup, then the resolution of up to two revealed parties.
		Weight::from_parts(DISCLOSE_COMPUTE, 0)
			.saturating_add(T::DbWeight::get().reads(3))
			.saturating_add(T::ZkVerifier::verify_weight(CircuitId::DisclosureProof, 1))
	}
}

impl WeightInfo for () {
	fn record() -> Weight {
		Weight::from_parts(50_000_000, 2_048)
	}

	fn disclose() -> Weight {
		Weight::from_parts(20_050_000_000, 8_192)
	}
}
